feat: Add the option to search films by title using both InMemoryFilm…
agluh/java-filmorate pull request #12
Opened 2022-06-08 21:59 UTC by Alex-M-Markov

…Storage and FilmDbStorage

feat: Add film search tests

2022-06-09 05:03 UTC, agluh requested changes
Отличная работа! (говорю прямо как мой ревьювер)
Но есть пара моментов, которые можно улучшить.
Ну и почему то все не могут удержаться, чтобы не править отступы в коде (погляди diff).

2022-06-09 05:03 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        return jdbcTemplate.query(SELECT_FILMS_BY_NAME_SUBSTRING, this::mapRowToFilm, "%" + query.toLowerCase()
Предлагаю эту конкатенацию убрать, а знаки процента внести в строку запроса `LIKE %?%`. Так запрос считывается понятнее, не надо лазить в код.

2022-06-09 05:03 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +import java.util.*;
Общих импортов лучше избегать.

2022-06-09 05:03 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            ", release_date, duration, mpa FROM films WHERE LOWER(name) LIKE ?";
На мой взгляд запятую надо оставить на первой строчке.

2022-06-09 05:03 UTC, agluh commented on src/test/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageTest.java
> +    void getFilmsBySearchFromMemory() {
А почему мы в тесте DB имплементации тестируем ImMemory вариант?

2022-06-09 07:49 UTC, BLRrubik commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            ", release_date, duration, mpa FROM films WHERE LOWER(name) LIKE ?";
Алексей правильно заметил, лучше использовать LIKE %?%

2022-06-09 08:10 UTC, Alex-M-Markov commented
> Отличная работа! (говорю прямо как мой ревьювер)
> Но есть пара моментов, которые можно улучшить.
> Ну и почему то все не могут удержаться, чтобы не править отступы в коде (погляди diff).

Спасибо! 

Судя по всему, ревьюер у нас один - Александр Куколев :-)

Отступы в основном правит Idea, а у меня есть привычка постоянно нажимать alt+ctrl+l. Честно ревертнул 80% изменений в части форматирования, иначе это выглядело бы совсем странно. Не знаю по какой причине, но она изначальный проект сильно форматирует.

2022-06-09 08:15 UTC, Alex-M-Markov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        return jdbcTemplate.query(SELECT_FILMS_BY_NAME_SUBSTRING, this::mapRowToFilm, "%" + query.toLowerCase()
Добрых полчаса бился с системой как раз по этому поводу. Изначально так и сделал, но она упорно не работала, поэтому пришлось делать контакенцию. 

Попробую еще раз, может быть дело было в чём-то другом.

2022-06-09 08:39 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +import java.util.*;
идея сама обобщать начинает после какого-то количества импортов, это как то можно отключить?

2022-06-09 08:41 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +import java.util.*;
хотел вопрос задать, а гитхаб меня в ревьюверы пихнул )

2022-06-09 08:42 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +import java.util.*;
Не знаю, я в правила импортировал гугловские настройки стилей, если нажать Ctrl + Alt + O, то он сам сгруппирует импорты и развернёт, если нужно, общие.

2022-06-09 09:19 UTC, Alex-M-Markov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +import java.util.*;
При четырех(если правильно помню) импортах из одного пакета Идея автоматически их объединяет как общий импорт при оптимизации.
Могу разделить, но она на каком-то
этапе может все вернуть. К тому же по какой-то причине она это всё-таки делает.

2022-06-09 09:23 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +import java.util.*;
Я могу пошарить файлик стилей для идеи, если их импортировать, будут требования как у меня)
https://www.dropbox.com/s/2pqgdt8tuie71w0/intellij-java-google-style.xml?dl=0

2022-06-09 09:27 UTC, Alex-M-Markov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            ", release_date, duration, mpa FROM films WHERE LOWER(name) LIKE ?";
Действую по заветам Яндекс.Практикума))
Мне тоже предложенный тобой вариант кажется более органичным.
Но именно за это я несколько раз получал комментарий от ревьюера. Что-то вроде: «символ в начале перенесенной строчки позволяет сразу увидеть, что это продолжение предыдущей». Могу перенести, совершенно не принципиально.

2022-06-09 09:28 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            ", release_date, duration, mpa FROM films WHERE LOWER(name) LIKE ?";
Первый раз о таком слышу. У нас везде так, сделай уж как везде, отбрехаюсь я перед ревьювером, если что)

2022-06-09 09:31 UTC, Alex-M-Markov commented on src/test/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageTest.java
> +    void getFilmsBySearchFromMemory() {
Полностью согласен. Искал тесты для InMemory реализации, но не смог их найти. Поэтому решил оставить тест здесь, т.к. он нужен для проверки функциональности. А отдельный класс с тестами InMemory решил не делать, поскольку тогда потребуется больший рефакторинг, нежели это подразумевается в этой ветке.

Куда его лучше будет перенести?

2022-06-09 09:45 UTC, agluh commented on src/test/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageTest.java
> +    void getFilmsBySearchFromMemory() {
Да никуда) Нам дали добро убить InMemory реализации в будущем. Пометь как deprecated) я потом удалю при чистке)

2022-06-09 11:00 UTC, Alex-M-Markov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            ", release_date, duration, mpa FROM films WHERE LOWER(name) LIKE ?";
Спасибо! Попробую исправить, мне самому такой вариант больше по душе.

2022-06-09 11:03 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        return jdbcTemplate.query(SELECT_FILMS_BY_NAME_SUBSTRING, this::mapRowToFilm, "%" + query.toLowerCase()
Пиши, если что, у меня нет идей, почему это может не работать.

2022-06-09 20:38 UTC, Alex-M-Markov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            ", release_date, duration, mpa FROM films WHERE LOWER(name) LIKE ?";
https://stackoverflow.com/questions/55499110/jdbc-template-giving-error-for-query-using-like
Всё-таки тут не победить систему

2022-06-09 20:41 UTC, Alex-M-Markov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        return jdbcTemplate.query(SELECT_FILMS_BY_NAME_SUBSTRING, this::mapRowToFilm, "%" + query.toLowerCase()
На самом деле очень интересно, почему не работает. Может расскажут наши наставники, что за фигня за этим скрывается.

2022-06-09 20:58 UTC, agluh approved these changes

2022-06-09 20:59 UTC, Alex-M-Markov commented on src/test/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageTest.java
> +    void getFilmsBySearchFromMemory() {
Ок, пометил и прокомментировал

2022-06-09 20:59 UTC, Alex-M-Markov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            ", release_date, duration, mpa FROM films WHERE LOWER(name) LIKE ?";
Готово

2022-06-10 20:29 UTC, Ben1t0 approved these changes

2022-06-11 10:27 UTC, merged