Add recommendations
agluh/java-filmorate pull request #13
Opened 2022-06-09 10:10 UTC by BLRrubik

2022-06-09 10:29 UTC, agluh requested changes
У меня основная притензия к сваггеру здесь. В задачу это не входило. К тому же даже коммита нету, который бы давал понять, что там прикрутили сваггер. Мало ли мы захотим грохнуть фичу рекомендаций, но оставить сваггер - поди ещё раздели их.

А в принципе, документация это хорошо. Предлагаю убрать эту фичу в отдельный PR, пусть там и сломаются тесты, я его волью "насильно". Главное, что будет видно откуда это взялось.

2022-06-09 10:29 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getRecommendations(Long id) {
Если нет нужды именно в списке, имеет смысл вернуть просто коллекцию. Чем общее контракт, тем лучше. Вдруг ты в реализации решишь вернуть Set - с твоим возвращаемым значением это уже не выйдет сделать.

2022-06-09 10:29 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/RecommendationStorage.java
> +public interface RecommendationStorage {
На мой взгляд это можно перенести в FilmReadModel - ты же возвращаешь фильмы, просто по хитрой выборке.

2022-06-09 10:29 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return ResponseEntity.of(Optional.of(filmService.getRecommendations(id)));
Это какая то магческая конструкция. Зачем тут опшенал и ResponseEntity? Просто верни коллекцию от сервиса, как выше в коде в примере getMostPopularFilms.

2022-06-09 11:06 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getRecommendations(Long id) {
И ещё бы попонятнее назвать метод или параметр. Что такое id? Для чего я получаю рекомендации?

2022-06-09 12:31 UTC, agluh approved these changes

2022-06-09 22:49 UTC, Alex-M-Markov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +    @Override
В принципе, теперь все классы для хранения InMemory можно пометить как @⁠Deprecated
Я таким образом пометил соответствующие тесты.

2022-06-09 22:49 UTC, Alex-M-Markov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        return jdbcTemplate.query(SELECT_RECOMMENDATIONS, this::mapRowToFilm,id,id,id);
Может быть существует возможность передать параметр id (filmId) один раз, а уже в запросе ему назначить алиас и дублировать уже там?

2022-06-09 22:49 UTC, Alex-M-Markov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +
Тесты ты не писал на метод? 
В принципе можно конечно сэкономить время и подождать, когда их выкатит Практикум.

2022-06-12 11:10 UTC, Alex-M-Markov approved these changes

2022-06-12 13:04 UTC, merged