New features by specs
agluh/java-filmorate pull request #16
Opened 2022-06-13 08:43 UTC by agluh

New implemented features:
- film recommendations
- film reviews
- events for users
- filter for films by genre and release year
- deleting of users and films
- search by films

Also added support of genres for films (required by tests)

2022-06-13 16:30 UTC, kukolev requested changes

2022-06-13 16:30 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/EventDbStorage.java
> +    public static final String INSERT_EVENT =
Константу нужно сделать приватной, т.к. она используется только в этом классе и не нужно, чтобы к ней был доступ извне.

Аналогично нужно поправить доступы к константам ниже.

2022-06-13 16:30 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
>      public static final String SELECT_FILM =
Константу нужно сделать приватной, т.к. она используется только в этом классе и не нужно, чтобы к ней был доступ извне.

Аналогично нужно поправить доступы к константам ниже.

2022-06-13 16:30 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +    public static final String SELECT_GENRE =
Константу нужно сделать приватной, т.к. она используется только в этом классе и не нужно, чтобы к ней был доступ извне.

Аналогично нужно поправить доступы к константам ниже.

2022-06-13 16:30 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
>      public static final String SELECT_USER =
Константу нужно сделать приватной, т.к. она используется только в этом классе и не нужно, чтобы к ней был доступ извне.

Аналогично нужно поправить доступы к константам ниже.

2022-06-13 16:30 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/events/listener/FriendshipEventListener.java
> +            "FRIEND",
Эти идентификаторы здесь и ниже лучше оформить как константы. Константы позволят избежать опечаток при дублировании. Также константы самодокументируемые - можно в названии константы описать ее смысл.

Аналогично нужно поправить везде ниже.

2022-06-13 16:30 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/events/listener/LikeEventListener.java
> +            "LIKE",
Эти идентификаторы здесь и ниже лучше оформить как константы. Константы позволят избежать опечаток при дублировании. Также константы самодокументируемые - можно в названии константы описать ее смысл.

Аналогично нужно поправить везде ниже.

2022-06-13 16:30 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/events/listener/ReviewEventListener.java
> +            "REVIEW",
Эти идентификаторы здесь и ниже лучше оформить как константы. Константы позволят избежать опечаток при дублировании. Также константы самодокументируемые - можно в названии константы описать ее смысл.

Аналогично нужно поправить везде ниже.

2022-06-13 16:30 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/MpaRating.java
> +    G("G"),
По моему можно упростить, если вообще отказаться от поля name, которое сейчас дублирует название каждого элемента.

2022-06-13 16:30 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (query != null && by.equals("title")) {
Эти идентификаторы здесь и ниже лучше оформить как константы. Константы позволят избежать опечаток при дублировании. Также константы самодокументируемые - можно в названии константы описать ее смысл.

2022-06-14 06:35 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/EventDbStorage.java
> +    public static final String INSERT_EVENT =
Готово.

2022-06-14 06:36 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
>      public static final String SELECT_FILM =
Готово.

2022-06-14 06:36 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +    public static final String SELECT_GENRE =
Готово.

2022-06-14 06:36 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
>      public static final String SELECT_USER =
Готово.

2022-06-14 06:36 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/events/listener/FriendshipEventListener.java
> +            "FRIEND",
Готово.

2022-06-14 06:36 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/events/listener/LikeEventListener.java
> +            "LIKE",
Готово.

2022-06-14 06:36 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/events/listener/ReviewEventListener.java
> +            "REVIEW",
Готово.

2022-06-14 06:38 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/model/MpaRating.java
> +    G("G"),
Это поле хранит человекочитаемое значение, которое у нас проверяют приёмочные тесты. А его значение не везде совпадает с названием (например, `NC_17` vs `NC-17`).

2022-06-14 06:38 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (query != null && by.equals("title")) {
Готово.

2022-06-14 18:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/events/listener/FriendshipEventListener.java
> +    private static final String FRIEND = "FRIEND";
Эти константы ничего не говорят о смысле констант. Код также остался непонятным, просто, по сути вместо литералов появились константы. Будет значительно лучше, если в названии констант будет отражен и их смысл. Именно так можно достичь самодокументированности кода.

Аналогично нужно поправить в LikeEventListener и .ReviewEventListener.

2022-06-14 18:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/MpaRating.java
> +    G("G"),
Окей, принято.

2022-06-14 19:09 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/events/listener/FriendshipEventListener.java
> +    private static final String FRIEND = "FRIEND";
Переименовали в более понятные)

2022-06-15 07:45 UTC, kukolev approved these changes

2022-06-15 07:55 UTC, merged