Add friends and likes
agluh/java-filmorate pull request #2
Opened 2022-05-02 13:52 UTC by agluh

2022-05-02 20:09 UTC, kukolev requested changes

2022-05-02 20:09 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        boolean isNewLike = likeService.doLike(userId, filmId);
Переменная нигде не используется. Неиспользуемый код нужно убирать, чтобы не отвлекал.

2022-05-02 20:09 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        boolean wasLiked = likeService.doUnlike(userId, filmId);
Переменная нигде не используется. Неиспользуемый код нужно убирать, чтобы не отвлекал.

2022-05-02 20:09 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        boolean areNewFriends = friendshipService.makeFriends(userId, friendId);
Переменная нигде не используется. Неиспользуемый код нужно убирать, чтобы не отвлекал.

2022-05-02 20:09 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        boolean wasFriends = friendshipService.unfriendUsers(userId, friendId);
Переменная нигде не используется. Неиспользуемый код нужно убирать, чтобы не отвлекал.

2022-05-03 07:27 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        boolean isNewLike = likeService.doLike(userId, filmId);
Неиспользуемую локальную переменную удаил.

2022-05-03 07:28 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        boolean wasLiked = likeService.doUnlike(userId, filmId);
Неиспользуемую локальную переменную удаил.

2022-05-03 07:28 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        boolean areNewFriends = friendshipService.makeFriends(userId, friendId);
Неиспользуемую локальную переменную удаил.

2022-05-03 07:28 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        boolean wasFriends = friendshipService.unfriendUsers(userId, friendId);
Неиспользуемую локальную переменную удаил.

2022-05-03 09:29 UTC, kukolev approved these changes

2022-05-03 10:00 UTC, merged