Add database schema and query examples
agluh/java-filmorate pull request #4
Opened 2022-05-14 14:06 UTC by agluh

2022-05-15 21:23 UTC, kukolev requested changes

2022-05-15 21:23 UTC, kukolev commented on docs/db/source.txt
> +user_id PK int autoincrement
Здесь и ниже int как PK не самое лучшее решение. Может случиться переполнение int в высоконагруженном сервисе. Лучше заменить на long.

2022-05-16 07:29 UTC, agluh commented on docs/db/source.txt
> +user_id PK int autoincrement
Если мы будет использовать именно [PostgreSQL](https://www.postgresql.org/docs/current/datatype-numeric.html), то для PK с автоинкрементом можно взять специальный тип данных `bigserial`, а для FK на него в других таблицах - `bigint`. Подойдёт такой вариант?

2022-05-17 14:26 UTC, kukolev commented on docs/db/source.txt
> +user_id PK int autoincrement
Да, вполне!

2022-05-17 19:31 UTC, kukolev requested changes

2022-05-17 19:31 UTC, kukolev commented on docs/db/source.txt
>  genre
По моему связь 1 ко многим film-film_genre ошибочна. Теперь получается, что у фильма может быть несколько жанров. Согласно ТЗ у фильма должен быть один жанр. Проще сделать жанр просто полем в film.

2022-05-17 19:31 UTC, kukolev commented on docs/db/source.txt
>  mpaa
По моему рейтинг фильма можно сделать просто полем в film. Выделять рейтинг в отдельную сущность не имеет смысла.

2022-05-18 06:46 UTC, agluh commented on docs/db/source.txt
>  genre
По нашему ТЗ у фильма может быть как раз несколько жанров.

2022-05-18 06:46 UTC, agluh commented on docs/db/source.txt
>  mpaa
Хорошо.

2022-05-18 06:53 UTC, kukolev approved these changes

2022-05-18 06:56 UTC, merged