Add reviews
agluh/java-filmorate pull request #7
Opened 2022-06-06 23:04 UTC by Ben1t0

2022-06-07 05:20 UTC, agluh commented
А своих тестов нету, кстати? На контроллер, интеграционных.

2022-06-07 15:53 UTC, TodayIsMay commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.info("User {} like review {}", userId, reviewId);
Я докопаюсь до грамматики: likes или liked тогда уж)

2022-06-07 15:53 UTC, TodayIsMay commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.info("User {} like review {}", userId, reviewId);
Ну и во всех логах то же самое

2022-06-07 16:02 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.info("User {} like review {}", userId, reviewId);
я только свои логи поменяю, а то потом мерджить устанем

2022-06-07 16:03 UTC, agluh requested changes

2022-06-07 16:03 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/service/exception/ReviewNotFoundException.java
> +/**
Обычно я после package оставляю пустую строку.

2022-06-07 16:03 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    Collection<Review> getReviewsByFilmId(long id);
Я предлагаю продолжть следовать логике с выделением read model и перенести это туда.

2022-06-07 16:03 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewUsefulStorage.java
> +public interface ReviewUsefulStorage {
А зачем этот репозиторий отдельно? Почему не использовать ReviewStorage?

2022-06-07 16:03 UTC, agluh commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
Лихо ты, конечно, схему поменял. Я понимаю, красоту навести всегда хорошо, но в задачу это не входило.

2022-06-07 16:03 UTC, agluh commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS useful_rates
А зачем хранить рейтинг отзыва отдельно? У нас требуют знать, кто и когда менял рейтинг? Вроде это просто счётчик в объекте ревью. Зачем такие сложности?

2022-06-07 16:03 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    public Review getUsefulRate(Review review) {
Мне кажется это переусложнение. Полезность отзыва это просто поле, на мой взгляд.

2022-06-07 16:03 UTC, agluh commented on postman/add-reviews-tests.json
> +{
А что это за файл? У нас вроде централизовано от Владимира прилетает, по названию ветки.

2022-06-07 16:03 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage, LikeStorage, FilmReadModel, ReviewStorage, ReviewUsefulStorage {
А почему ты добавил реализацию сюда, а не сделал отдельный ReviewDbStorage?

2022-06-07 16:03 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            "SELECT user_id, film_id, created_at FROM likes WHERE user_id = ? AND film_id = ?";
Где то писал уже - в задачу не входила смена именования в столбиках существующей базы, как юы этого не хотелось.

2022-06-07 16:03 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +            + " FROM users AS u"
Сломал схему так, где не требовала задача.

2022-06-07 16:03 UTC, agluh commented on src/main/resources/data.sql
> +INSERT INTO genres (name)
В задаче ничего не было про жанры. Не стоит менять чужой код, как мне кажется.

2022-06-07 16:03 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/service/UsefulReviewService.java
> +public class UsefulReviewService {
А зачем отдельный класс под useful ревью? Почему не сделать это же в ReviewService?

2022-06-07 16:05 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/service/UsefulReviewService.java
> +public class UsefulReviewService {
Можно попробовал по аналогии с твоим кодом раздербанить все что можно

2022-06-07 16:06 UTC, Ben1t0 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
С базой вопрос закрыт ?)

2022-06-07 16:06 UTC, Ben1t0 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS useful_rates
рейтинг хранится в БД и его надо оттуда запрашивать каждый раз, это подтвердил Владимир Иванов

2022-06-07 16:07 UTC, Ben1t0 commented on postman/add-reviews-tests.json
> +{
это мои тесты можно снести, забыл удалить

2022-06-07 16:08 UTC, agluh commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
Да, но я бы всё равно так не делал)

2022-06-07 16:08 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +            + " FROM users AS u"
то есть?

2022-06-07 16:08 UTC, agluh commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS useful_rates
Эмм. Это как?

2022-06-07 16:09 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +            + " FROM users AS u"
Это к тому же вопросу про правку таблиц, где не надо было, писал вчера же.

2022-06-07 16:10 UTC, Ben1t0 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS useful_rates
как отслеживать кто уже лайкнул а кто дислайкнул, как ты запретишь пользователь несколько раз лайкнуть или дислайкнуть отзыв?

2022-06-07 16:10 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/service/UsefulReviewService.java
> +public class UsefulReviewService {
Ну, я вроде не ради дербана дербанил)

2022-06-07 16:11 UTC, agluh commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS useful_rates
А у нас в ТЗ написано, что можно несколько раз лайкать один и тот же фильм? Ты часто такое видел?

2022-06-07 16:11 UTC, agluh commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS useful_rates
Ааа. Всё, дошло)

2022-06-07 16:11 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            "SELECT user_id, film_id, created_at FROM likes WHERE user_id = ? AND film_id = ?";
Я писал что не заводилось с базой 'user' хоть убей хз почему

2022-06-07 16:12 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            "SELECT user_id, film_id, created_at FROM likes WHERE user_id = ? AND film_id = ?";
Ладно, это закрыли уже тоже.

2022-06-07 16:14 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    public Review getUsefulRate(Review review) {
там ниже обсуждение, это я закрою

2022-06-07 16:15 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    public Review getUsefulRate(Review review) {
Ага.

2022-06-07 16:16 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/service/UsefulReviewService.java
> +public class UsefulReviewService {
ну я честно говоря не до конца понял зачем ты некоторые вещи разделил, да в полне могу перенести в ReviewService

2022-06-07 16:17 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    Collection<Review> getReviewsByFilmId(long id);
то есть? там где то ты спрашиваешь почему я вообще не сделал отдельный "ReviewDBStorage implements ReviewStorge"

2022-06-07 16:18 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/service/UsefulReviewService.java
> +public class UsefulReviewService {
Имхо тут всё таки близкие понятия - ревью и оценка ревью. Так по идее бы и лайксервис можно в фильмы внедрить, я просто забыл, потому он лежит отдельно.

2022-06-07 16:19 UTC, Ben1t0 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS useful_rates
закрываю? или какие то вопросы по реализации?

2022-06-07 16:20 UTC, agluh commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS useful_rates
Да нет, хотя как то таблица называется странно. Но ладно, добро)

2022-06-07 16:21 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/service/UsefulReviewService.java
> +public class UsefulReviewService {
Ок перенесу, не закрывай, иначе забуду

2022-06-07 16:21 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    Collection<Review> getReviewsByFilmId(long id);
Нет, я предлагал объединить сервисы, но разделить интерфейсы у репозиториев

2022-06-07 16:22 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewUsefulStorage.java
> +public interface ReviewUsefulStorage {
перенесу

2022-06-07 16:22 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewUsefulStorage.java
> +public interface ReviewUsefulStorage {
Понял, что это для реализации нужно, закрываю.

2022-06-07 16:23 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/service/UsefulReviewService.java
> +public class UsefulReviewService {
Да по идее не надо закрывать то, что ты собрался править.

2022-06-07 16:24 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/service/UsefulReviewService.java
> +public class UsefulReviewService {
Навреное) А может и надо. Надо поглядеть, как будет выглядеть это всё после нового коммита.

2022-06-07 17:38 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    Collection<Review> getReviewsByFilmId(long id);
не понял, ты меня спросил почему я не вынес ReviewStorage, ReviewUsefulStorage в отдельный ReviewDbStorage (https://github.com/agluh/java-filmorate/pull/7#discussion_r890771128) . Как ты хочешь чтобы это выглядело?

2022-06-07 17:46 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    Collection<Review> getReviewsByFilmId(long id);
Я предлагаю так:
один ReviewService, где все задачи с ревью
для Review -> ReviewStorage (save, getById) + ReviewReadModel (все остальные запросы типа get)
Оба ReviewStorage  и ReviewReadModel  можно реализовать в одном ReviewDbStorage

Примерно такая же схема с рейтингом для ревью, но там вроде нету как таковой read model, поэтому там будет только свой Storage. Для него можно или сделать DbStorage, или воткнуть в тот же ReviewDbStorage.

Как то так.

2022-06-08 05:38 UTC, agluh requested changes
Ещё есть вопросы по архитектуре у меня слегка.

2022-06-08 05:38 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewReadModel.java
> +    Optional<Review> getReview(long id);
Этот метод по идее можно оставить в основном репозитории.

2022-06-08 05:38 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void deleteMark(long reviewId, long userId);
Вот эти три метода - я как то не любитель репозиториев, которые выполняют логику. Репозиторий хранит и отдаёт по запросу. Он не ставит лайки и дизлайки. Если взять пример с Friendship - там отдельный объект и свой репозиторий для этой сущности, хоть сущность по сути просто запись в таблице связей.

2022-06-08 05:38 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    Review getUsefulRate(Review review);
Я вот глядя на сигнатуру метода не понимаю, что он делает от слова совсем. Может назвать иначе или док написать?

2022-06-08 08:17 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewReadModel.java
> +    Optional<Review> getReview(long id);
Оставил в reviewreadmodel один метод ?

2022-06-08 08:19 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewReadModel.java
> +    Optional<Review> getReview(long id);
Да, почему нет)

2022-06-08 08:20 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewReadModel.java
> +    Optional<Review> getReview(long id);
Ок

2022-06-08 08:41 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void deleteMark(long reviewId, long userId);
так тут вся работа этих  методов добавить или удалить строчку из БД вот и вся логика. Ты хочешь чтобы я вынес эти методы в ReviewLikeStorage?

2022-06-08 08:46 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void deleteMark(long reviewId, long userId);
Во Friendship тоже по идее хранится только два числа. Но FrienshipStorage не имеет методов addFriend и deleteFriend. Он имеет методы типа "сохранить объект, представляющий дружбу". Вот я полагал, что тут тоже будет некий "объект, представляющий лайк отзыву" и ты его просто или сохранил/поменял или удалил. Если завтра надо будет хранить дату утсановки лайка и погоду на луне в этот день, ты тоже будешь это в параметрах репозиторию передавать?

2022-06-08 08:52 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void deleteMark(long reviewId, long userId);
ты хочешь целый объект создать который будет отвечать за лайки ревью, и ими оперировать? там же на выходе от всех этих лайков только Int с общим рейтингом
Я походу не очень понял тебя

2022-06-08 08:54 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void deleteMark(long reviewId, long userId);
Да, объект для лайков ревью. Как и для лайков фильмов, собственно.

2022-06-08 08:59 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void deleteMark(long reviewId, long userId);
На мой взгляд это как то слишком, но в целом конечно могу попробовать

2022-06-08 09:04 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void deleteMark(long reviewId, long userId);
Ну, у нас всё же объектный подход. А ты просишь хранилище напрямую примитивы сохранить)

2022-06-08 14:18 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    Review getUsefulRate(Review review);
Согласен, все переделал.

2022-06-08 14:19 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void deleteMark(long reviewId, long userId);
Все, пока переделывал понял ) так лучше, у меня логика в хранилище была это не правильно.

2022-06-08 14:27 UTC, agluh approved these changes
Всё отлично! Чуть в одном месте только форматирование поправить и можно мержить.

2022-06-08 14:27 UTC, agluh commented on src/main/java/ru/yandex/practicum/filmorate/model/ReviewLike.java
> +    }
Скобочка уплыла)

2022-06-08 14:32 UTC, Ben1t0 commented on src/main/java/ru/yandex/practicum/filmorate/model/ReviewLike.java
> +    }
Я по ней Ctrl+A Ctrl+Alt+L жахну

2022-06-09 06:57 UTC, TodayIsMay approved these changes

2022-06-09 08:50 UTC, agluh commented
Что то я проглядел этот момент на ревью. Вот этот метод по идее не должен быть в сервисе. Он должен быть в сторадже - то есть сторадж тебе отдаёт уже готовый объект.
https://github.com/agluh/java-filmorate/blob/500ee1b39161f881ed1bd2ccbf3285d8581fdcf7/src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java#L108

2022-06-09 20:07 UTC, agluh approved these changes
Отличная работа, всё по делу)

2022-06-11 11:30 UTC, merged